apiVersion: v1
kind: Secret
metadata:
  name: finance-assistant-secrets
  namespace: finance-assistant
type: Opaque
data:
  ES_HOST: "<BASE64_OF_HTTPS_ELASTIC_ENDPOINT>"
  ES_API_KEY: "<BASE64_OF_ES_API_KEY>"
