name: build-and-push-image

on:
  push:
    branches: [ main, master ]
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "llm-app/**"
      - ".github/workflows/build.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  # Final image will be ghcr.io/<user>/<repo>/finance-document-assistant-rag-agents
  IMAGE_NAME: ghcr.io/${{ github.repository }}/finance-document-assistant-rag-agents

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
